### ISSUE TITLE
jarjar failed handling org.xerial.snappy:snappy-java:1.1.8.2

### ISSUE THREAD

**Issue by jameslan** [google/bazel-common#132]
Error message:

```
Error: duplicate files in merged jar: org/xerial/snappy/VERSION~
```

Found the following code in `jarjar_runner.sh`:

```
duplicate_files="$(find * -type f -regex '.*~[0-9]*$')"
if [[ -n "${duplicate_files}" ]]; then
  echo "Error: duplicate files in merged jar: ${duplicate_files}"
  exit 1
fi
```
What is it for?

FYI
The contents of `org/xerial/snappy/VERSION`:
```
SNAPPY_VERSION=1.1.8
BITSHUFFLE_VERSION=0.3.2
```
and the content of `org/xerial/snappy/VERSION~`:
```
SNAPPY_VERSION=1.1.7
BITSHUFFLE_VERSION=0.3.2
```

**Comment by netdpb** [comment]
That part of the script merges files that appear in more than one JAR's `META-INF` directory by concatenating them, as long as you pass the right argument to the rule's [`merge_meta_inf_files` parameter](https://github.com/google/bazel-common/blob/master/tools/jarjar/jarjar.bzl#L54).

For some reason more than one of your JARs contains an `org/xerial/snappy/VERSION` file. What arguments are you passing to `jarjar_library`?

**Comment by jameslan** [comment]
Also, may I ask which command generates the file with tilde postfix? I tried the default zipper `@bazel_tools//tools/zip:zipper`, to extract the same jar twice to the same location, but didn't find any file with tlide.

**Comment by netdpb** [comment]
The `-B` option passed to `unzip` [here](https://github.com/google/bazel-common/blob/9d1beb9294151cb1b28cd4b4dc842fd7559f9147/tools/jarjar/jarjar_runner.sh#L20) creates backup files.

We use this to prevent you from having a bug when two JARs contain the same file.

If `org.xerial.snappy:snappy-java` contains a `VERSION~` file, that's likely a bug in their release. It looks like it was introduced in 1.1.7, since it's not there in 1.1.4.

I'm going to close this bug because I think the underlying problem is with `snappy-java`.
